name: Release on tag

on:
  push:
    tags:
      - '*'

jobs:
  build-test-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Get version from Git
        id: get_version
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          echo "VERSION=$TAG" >> $GITHUB_OUTPUT

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Unit Tests
        run: go test ./... -v

      - name: Build Windows x86-64 binary
        run: |
          GOOS=windows GOARCH=amd64 go build \
            -ldflags="-X 'main.version=${{ steps.get_version.outputs.VERSION }}'" \
            -o tiktok-favvideo-downloader-x86_64.exe .

      - name: Build Windows-on-ARM binary (ARM64)
        run: |
          GOOS=windows GOARCH=arm64 go build \
            -ldflags="-X 'main.version=${{ steps.get_version.outputs.VERSION }}'" \
            -o tiktok-favvideo-downloader-ARM64.exe .

      # 7. Create a new draft GitHub release with this version
      - name: Publish release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            tiktok-favvideo-downloader-x86_64.exe
            tiktok-favvideo-downloader-ARM64.exe
            README.md
